export { default as EdtechNavbar } from './Navbar';
export { default as EdtechFooter } from './Footer';
export { default as AboutHeroSection } from './AboutHeroSection';
export { default as TestimonialsSection } from './TestimonialsSection';
export { default as BestCourseSection } from './BestCourseSection';
export { default as CourseHeroSection } from './CourseHeroSection';
export { default as ContactHeroSection } from './ContactHeroSection';
export { default as ContactForm } from './ContactForm';
export { default as AllCoursesSection } from './AllCoursesSection';
